# Generated by Django 4.0 on 2023-11-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=500)),
                ('tags', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='news_app/media')),
            ],
        ),
    ]
